services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./frontend:/app/frontend
      - ./frontend/static:/app/frontend/static
      - ./frontend/templates:/app/frontend/templates
    restart: unless-stopped
    depends_on:
      - backend
  
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5646:5646"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./backend:/app/backend
    restart: unless-stopped